TEXTURES = [
    "DLC2BasaltTop.dds", 
    "Volcanic_Ash_01.dds", 
    "Volcanic_Ash_Rocks_01_D.dds", 
    "Volcanic_Ash_Tundra_02.dds",
    "Volcanic_Ash_Tundra_04.dds",
    "CoastBeach01.dds", 
    "Dirt02.dds", 
    "FallForestDirt01.dds", 
    "FallForestGrass01.dds",
    "FallForestLeaves01.dds", 
    "FieldGrass01.dds", 
    "FieldGrass02.dds", 
    "FrozenMarshIce01.dds", 
    "MineralPoolTerrace.dds",
    "ReachMoss01.dds", 
    "ReachMossyRocks01.dds", 
    "RiverbedEdge.dds", 
    "Rocks01.dds", 
    "Snow01.dds", 
    "Snow02.dds",
    "SnowRocks01.dds", 
    "Tundra01.dds", 
    "TundraRocks01.dds", 
    "VolcanicTundraDirt01.dds", 
    "VolcanicTundraGravel01.dds",
    "VolcanicTundraMinerals01.dds", 
    "VolcanicTundraRocks01.dds",
    "WRDirtbase.dds", 
    "WRFieldGrass01.dds",
    "MineFloorDirt01.dds"
]

textures_lowered = [i.lower() for i in TEXTURES]